// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";
import type { User } from "./User";

export interface Content { user: User, links: Array<Link>, }